
server:
  port: 8081
 
spring:
  datasource:
    username: root
    password: ttn991122
    url: jdbc:mysql://localhost:3306/wenhua_desert?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations:
    - file:D:/webroot
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wenhuadesert.oa.**.model
 
#showSql
logging:
  level:
    com.wenhuadesert.oa.goods.mapper : debug
